---
- name: "Install sample data : Deploy"
  shell: >
    {{ magento2_install_path }}/bin/magento sampledata:deploy
  args:
      creates: "{{ magento2_install_path }}/pub/media/catalog"

- name: "Install sample data : Run upgrade"
  shell: >
    {{ magento2_install_path }}/bin/magento setup:upgrade
